---
- hosts: "{{hostlist}}"
  vars:
    packages:
    - desktop
    - better-defaults
    - erlang
    - flycheck
    - git-gutter
    - magit
    - org
    - paredit
    - python-mode
    - tramp
    - workgroups2
    - yasnippet
  roles:
    - zsh
    - oh-my-zsh
    - tmux
    - iterm
    - emacs
    - httpie