- name: install minikube
  homebrew_cask:
   name: minikube
   state: present
- name: set default memory
  shell: minikube config set memory 8192
- name: set default cpus
  shell: minikube config set cpu 4